import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["100","200","300","400","500","600","700"],
});

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${montserrat.className} antialiased`}>
        {children}
        </body>
        </html>
    );
}